__author__ = 'weifshen'

_format_data = {
	'sources-filter' : ['TPGW','CB','Hecate','Linus','WebEx-client'],
	#'sources-filter' : ['TPGW','Hecate','Linus'],
	'start-with-pattern' : '\[(\d+[/]\d+[/]\d+ \d+[:]\d+[:]\d+[.]\d+) ',
	'log-levels-pattern': {
		'info'    : ' Info:',
		'warning' : ' Warning:',
		'error'   : ' Error:',
		'debug'   : ' Detail:',
	},
	'source-pattern': 'source:([^,]*)',
	'target-pattern': 'target:([^,]*)',
	'confId-locusId-map': {'pattern':'.*meeting_id=(.*)_.*locus\/api\/v(1|2|3)\/loci\/(.*).*$', 'confId-Idx':1, 'locusId-Idx':3},
}

_events_data = {
	'conference-events' : {
		'OnJoinWBXMeetingRequest [PETA]' : {'source':'Tahoe','target':'TPGW','label':'creating cascading link request'},
		'OnCreateJoinMeetingConfirm [PETA],uRoomId=' : {'source':'TPGW','target':'Thaoe','label':'creating cascading link confirm'},
		'CreateMeeting,' : {'source':'TPGW','target':'CB','label':'creating conference'},
		'OnCreateJoinMeetingConfirm [PETA],uRoomId=' : {'source':'CB','target':'TPGW','label':'conf created'},
		', callbackURL=' : {'source':'Hecate','target':'TPGW','label':'join conf'},
		'OnMeetingClosedIndication [PETA],uRoomId' : {'source':'CB','target':'TPGW','label':'conf closed'},
		'LeaveMeeting,m_iStatus=3' : {'source':'TPGW','target':'CB','label':'leave conference'},
		#'OnUserEjected [PETA],roomId=' : {'source':'CB','target':'TPGW','label':'eject user','forward':'Hecate'},
		'OnAddEndpointRequest,userid=' : {'source':'Hecate','target':'TPGW','label':'endpoint join','forward':'CB'},
		'OnCreateJoinMeetingConfirm [PETA],err=' : {'source':'CB','target':'TPGW','label':'endpoint/dummy user joined'},
		'OnRemoveEndpointRequest [PETA],userId=' : {'source':'Hecate','target':'TPGW','label':'endpoint leave'},
		'LeaveMeeting,m_iStatus=8' : {'source':'TPGW','target':'CB','label':'endpoint leave'},
		#'OnSetMuteStatusRequest [PETA],userId=' : {'source':'Hecate','target':'TPGW','label':'mute user','forward':'CB'},
		'OnHostChangedIndication,uNewHostId=' : {'source':'CB','target':'TPGW','label':'Host changed'},
		'OnActivePresenterUpdateRequest [PETA]' : {'source':'Hecate','target':'TPGW','label':'presenter changed','forward':'CB'},
		'1:: OnPresenterChangedIndication' : {'source':'CB','target':'TPGW','label':'Presenter changed'},
		'NotifyWebexUserJoin, WEBEX_TRACKINGID=' : {'source':'CB','target':'TPGW','label':'WebEx user join','forward':'Locus'},
		'NotifyWebexUserLeave, WEBEX_TRACKINGID=' : {'source':'CB','target':'TPGW','label':'WebEx user leave','forward':'Locus'},
		'NotifyVideoCallbackUserLeave, WEBEX_TRACKINGID=' : {'source':'CB','target':'TPGW','label':'video call back user leave','forward':'Locus'},
		'NotifyUserExpelled, WEBEX_TRACKINGID=' : {'source':'CB','target':'TPGW','label':'user expelled','forward':'Locus'},
		'NotifyUserMuteStatus, WEBEX_TRACKINGID=' : {'source':'CB','target':'TPGW','label':'user mute status change','forward':'Locus'},
		'GetLocus, WEBEX_TRACKINGID=' : {'source':'TPGW','target':'Locus','label':'user mute status change'},
		'cascading link would be teared down' : {'source':'Hecate','target':'TPGW','label':'cascading link down via REST'},
		'OnMCUMeetingEndedNotify [PETA],reason=3' : {'source':'Tahoe','target':'TPGW','label':'cascading link down via sip'},
	},
	'session-events' : {
		'OnSessionCreatedIndication:4,' : {'source':'CB','target':'TPGW','label':'session created', 'separator-line':'before'},
		'OnSessionClosedIndication,AS' : {'source':'CB','target':'TPGW','label':'session closed', 'separator-line':'after'},
		'JoinSession [PETA],m_iStatus=8, uSessType=4' :{'source':'TPGW','target':'CB','label':'AS session join request','separator-line':'before'},
		'OnJoinSessionConfirm,type=4' :{'source':'CB','target':'TPGW','label':'AS session joined','separator-line':'after'},
	},
	'media-events' : {
		'HandleDataFromSpark, receive key frame' : {'source':'Linus','target':'TPGW','label':'key frame','forward':'WebEx-client'},
		'InputReceivedRtpDataFromWebEx,this is a key frame' : {'source':'WebEx-client','target':'TPGW','label':'key frame','forward':'Linus'},
		'OnMCUFullIntraRequest' : {'source':'Linus','target':'TPGW','label':'key frame request[SIP]'},
		'RequestIdrFrameFromAS' : {'source':'TPGW','target':'WebEx-client','label':'key frame request'},
		'OnPictureLossIndication' : {'source':'Linus','target':'TPGW','label':'key frame request[RTCP]'},
		'OnIDRRequest,uUsrId' : {'source':'WebEx-client','target':'TPGW','label':'key frame request'},
		'WBXFullIntraRequest ' : {'source':'TPGW','target':'Linus','label':'key frame request[SIP]'},
		'CMultiStreamRtpSession::RequestIDR' : {'source':'TPGW','target':'Linus','label':'key frame request[RTCP]'},
		'HandleSCR:' : {'source':'Linus','target':'TPGW','label':'SCR'},
		'OnSubScribe()' : {'source':'TPGW','target':'TPGW','label':'OnSubScribe'},
		'Announce(), availabe' : {'source':'TPGW','target':'TPGW','label':'Announce'},
		'SendSCA:' : {'source':'TPGW','target':'Linus','label':'SCA'},
		':: initialize,remote:' : {'source':'Linus','target':'TPGW','label':'init rtp session'},
		'UpdateRemoteInfo, remote:' : {'source':'Linus','target':'TPGW','label':'update remote info'},
	},
	'BFCP-events' : {
		'OnMCUPresenterGrabedNotify,floor status' : {'source':'Linus','target':'TPGW','label':'Grab floor'},
		'OnMCUPresenterReleasedNotify,floor status' : {'source':'Linus','target':'TPGW','label':'Release floor'},
		'OnWBXPresenterRevokedNotify' : {'source':'Linus','target':'TPGW','label':'Floor revoked'},
		'OnBFCPConnected,floor status:' : {'source':'Linus','target':'TPGW','label':'BFCP connected'},
		'GrabFloor,floor status' : {'source':'TPGW','target':'Linus','label':'Grab floor'},
		'OnWBXGrabPresenterConfirm,result:' : {'source':'Linus','target':'TPGW','label':'Grab floor confirm'},
		'ReleaseFloor,floor status:' : {'source':'TPGW','target':'Linus','label':'Release floor'},
		'OnWBXReleasePresenterConfirm' : {'source':'Linus','target':'TPGW','label':'Floor released confirm'},
	},
	'CI-events' : {
		'validate req_id' : {'source':'TPGW', 'target':'CI', 'label' : 'validate token'},
		'getBearerToken req_id' : {'source':'TPGW', 'target':'CI', 'label' : 'get bear token'},
		'handleGetBearerToken' : {'source':'CI', 'target':'TPGW', 'label' : 'get bear token response'},
		'getAccessToken req_id =' : {'source':'TPGW', 'target':'CI', 'label' : 'get access token'},
		'handleGetAccessToken current_tick=' : {'source':'CI', 'target':'TPGW', 'label' : 'get access token response'},
		'refreshAccessToken req_id =' : {'source':'TPGW', 'target':'CI', 'label' : 'refresh access token'},
		'handleRefreshAccessToken ,m_expires_tick=' : {'source':'CI', 'target':'TPGW', 'label' : 'refresh access token response'},
		'validate req_id =' : {'source':'TPGW', 'target':'CI', 'label' : 'validate access token from Hecate'},
		'handleGetTokenInfo validated scope=' : {'source':'CI', 'target':'TPGW', 'label' : 'validate access token response'},
		'GetResponseTrackingId' : {'source':'CI', 'target':'TPGW', 'label' : 'CI response'},
	}
}
